In [ ]:
import tushare as ts
#pro = ts.pro_api()
import os,sys
sys.path.append( os.path.dirname(os.getcwd()))
from utils.config import *

In [37]:
df = pro.adj_factor( trade_date='20250826')
df

        ts_code trade_date  adj_factor
0     000001.SZ   20250826    131.7878
1     000002.SZ   20250826    181.7040
2     000004.SZ   20250826      4.0639
3     000006.SZ   20250826     39.7400
4     000007.SZ   20250826      8.2840
...         ...        ...         ...
5448  920445.BJ   20250826      1.6005
5449  920489.BJ   20250826      1.8074
5450  920682.BJ   20250826      2.5804
5451  920799.BJ   20250826      3.1317
5452  920819.BJ   20250826      1.1328

[5453 rows x 3 columns]

In [35]:
df = pro.daily(ts_code='300502.SZ', start_date='20250825', end_date='20250826')
df

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,300502.SZ,20250826,298.00,300.90,282.04,282.04,296.12,-14.08,-4.7548,489957.24,1.422651e+07
1,300502.SZ,20250825,283.32,304.08,275.78,296.12,273.81,22.31,8.1480,587099.56,1.707747e+07

In [36]:
11.9448*282.04

3368.9113920000004

In [27]:
# df = pro.rt_k(ts_code='3*.SZ,6*.SH,0*.SZ,9*.BJ') #需要特殊权限
# df

In [30]:
df = pro.daily(trade_date='20250826')
df

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000001.SZ,20250826,12.45,12.50,12.30,12.36,12.45,-0.09,-0.7229,1383598.61,1709560.923
1,000002.SZ,20250826,6.98,7.03,6.90,6.99,7.16,-0.17,-2.3743,4379464.06,3051239.669
2,000004.SZ,20250826,10.14,10.75,10.14,10.75,10.24,0.51,4.9805,87842.02,93534.874
3,000006.SZ,20250826,7.23,7.42,7.16,7.31,7.33,-0.02,-0.2729,474261.99,344994.051
4,000007.SZ,20250826,7.61,8.00,7.53,7.73,7.61,0.12,1.5769,108813.64,84353.655
...,...,...,...,...,...,...,...,...,...,...,...
5411,920445.BJ,20250826,12.98,13.89,12.75,13.00,13.28,-0.28,-2.1084,103211.86,137042.227
5412,920489.BJ,20250826,23.74,23.75,23.28,23.30,23.75,-0.45,-1.8947,47172.15,110578.798
5413,920682.BJ,20250826,10.93,11.01,10.76,10.81,10.94,-0.13,-1.1883,69140.53,74923.321
5414,920799.BJ,20250826,62.51,64.47,62.44,62.71,63.50,-0.79,-1.2441,70899.24,450432.651
5415,920819.BJ,20250826,4.48,4.53,4.44,4.46,4.48,-0.02,-0.4464,164057.87,73410.785

In [38]:
df[df.ts_code=='688041.SH']

        ts_code trade_date  adj_factor
4606  688041.SH   20250826      1.0032

In [40]:
import time
time.strftime('%Y%m%d')

'20250826'