In [1]:
import tushare as ts
#pro = ts.pro_api()
import os,sys
sys.path.append( os.path.dirname(os.getcwd()))
ts.set_token('b9b26e60eb1a7ffb3578ae28d43d113c63be23d63b13a9feea0340f4')  # 替换为实际Token
pro = ts.pro_api('b9b26e60eb1a7ffb3578ae28d43d113c63be23d63b13a9feea0340f4')
#from utils.config import *

In [17]:
#同花顺热股
df = pro.ths_hot(trade_date='20230830', market='概念板块')

df.head(20)

,trade_date,data_type,ts_code,ts_name,rank,pct_change,current_price,hot,concept,rank_time,rank_reason
0,20230830,概念板块,885893.TI,国家大基金持股,9004,None,None,None,None,2023-08-30 16:30:08,None
1,20230830,概念板块,885905.TI,注册制次新股,9799,None,None,None,None,2023-08-30 16:30:08,None
2,20230830,概念板块,885866.TI,数字货币,10037,None,None,None,None,2023-08-30 16:30:08,None
3,20230830,概念板块,886031.TI,ChatGPT概念,10270,None,None,None,None,2023-08-30 16:30:08,None
4,20230830,概念板块,885957.TI,东数西算（算力）,10491,None,None,None,None,2023-08-30 16:30:08,None
5,20230830,概念板块,886042.TI,存储芯片,11650,None,None,None,None,2023-08-30 16:30:08,None
6,20230830,概念板块,885456.TI,互联网金融,12151,None,None,None,None,2023-08-30 16:30:08,None
7,20230830,概念板块,886013.TI,信创,14138,None,None,None,None,2023-08-30 16:30:08,None
8,20230830,概念板块,885942.TI,数据安全,15585,None,None,None,None,2023-08-30 16:30:08,None
9,20230830,概念板块,886052.TI,核污染防治,17130,None,None,None,None,2023-08-30 16:30:08,None
10,20230830,概念板块,885982.TI,华为欧拉,18473,None,None,None,None,2023-08-30 16:30:08,None
11,20230830,概念板块,886008.TI,减速器,20854,None,None,None,None,2023-08-30 16:30:08,None
12,20230830,概念板块,885907.TI,科创次新股,26581,None,None,None,None,2023-08-30 16:30:08,None
13,20230830,概念板块,886023.TI,数据确权,26672,None,None,None,None,2023-08-30 16:30:08,None
14,20230830,概念板块,885980.TI,华为鲲鹏,27445,None,None,None,None,2023-08-30 16:30:08,None
15,20230830,概念板块,885728.TI,人工智能,29188,None,None,None,None,2023-08-30 16:30:08,None
16,20230830,概念板块,885517.TI,机器人概念,35053,None,None,None,None,2023-08-30 16:30:08,None
17,20230830,概念板块,885756.TI,芯片概念,40434,None,None,None,None,2023-08-30 16:30:08,None
18,20230830,概念板块,886041.TI,数据要素,64399,None,None,None,None,2023-08-30 16:30:08,None
19,20230830,概念板块,885806.TI,华为概念,99628,None,None,None,None,2023-08-30 16:30:08,None

In [3]:
df = pro.daily_basic(ts_code='', trade_date='20180726', fields='ts_code,trade_date,turnover_rate,volume_ratio,pe,pb')

ConnectionError: HTTPConnectionPool(host='api.waditu.com', port=80): Max retries exceeded with url: /dataapi/daily_basic (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f12b1f94ca0>: Failed to resolve 'api.waditu.com' ([Errno -2] Name or service not known)"))

In [4]:
df = pro.query('daily_basic', ts_code='', trade_date='20180726',fields='ts_code,trade_date,turnover_rate,volume_ratio,pe,pb')

ConnectionError: HTTPConnectionPool(host='api.waditu.com', port=80): Max retries exceeded with url: /dataapi/daily_basic (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f12b1fa7b80>: Failed to resolve 'api.waditu.com' ([Errno -2] Name or service not known)"))

In [8]:
pro = ts.pro_api()

#提取000001全部复权因子
df = pro.query('adj_factor',  trade_date='20251219')
df

        ts_code trade_date  adj_factor
0     000001.SZ   20251219    134.5794
1     000002.SZ   20251219    181.7040
2     000004.SZ   20251219      4.0640
3     000006.SZ   20251219     39.7400
4     000007.SZ   20251219      8.2840
...         ...        ...         ...
5460  600337.SH   20251219     13.9599
5461  688807.SH   20251219      1.0000
5462  603388.SH   20251219      2.8870
5463  600800.SH   20251219      9.9040
5464  600730.SH   20251219      5.5698

[5465 rows x 3 columns]

In [5]:
df['adj_diff']=df.adj_factor - df.adj_factor.shift(1)
df[df.adj_diff!=0]

       ts_code trade_date  adj_factor  adj_diff
0    000001.SZ   20251024    134.5794       NaN
8    000001.SZ   20251014    131.7878   -2.7916
91   000001.SZ   20250611    127.7841   -4.0037
254  000001.SZ   20241009    125.0490   -2.7351
323  000001.SZ   20240625    125.0493    0.0003
324  000001.SZ   20240624    125.0496    0.0003
331  000001.SZ   20240613    116.7130   -8.3366

In [12]:
# df = ts.pro_bar(ts_code='000001.SZ', adj='qfq', start_date='20200101', end_date='20251026',adjfactor=True)

df = ts.pro_bar(ts_code='000001.SZ', start_date='19960101', end_date='20051026')
df

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000001.SZ,20051026,6.10,6.15,5.85,5.92,6.08,-0.16,-2.63,134733.62,80724.2598
1,000001.SZ,20051025,6.22,6.30,6.01,6.08,6.25,-0.17,-2.72,174573.06,106832.1372
2,000001.SZ,20051024,6.57,6.58,6.23,6.25,6.34,-0.09,-1.42,378669.40,241903.5862
3,000001.SZ,20051021,6.28,6.34,6.04,6.34,5.76,0.58,10.07,177062.85,111927.9344
4,000001.SZ,20050927,5.99,5.99,5.75,5.76,5.94,-0.18,-3.03,50313.24,29231.8153
...,...,...,...,...,...,...,...,...,...,...,...
2327,000001.SZ,19960108,6.20,6.23,6.12,6.20,6.26,-0.06,-0.96,3064.00,1888.8291
2328,000001.SZ,19960105,6.35,6.40,6.25,6.26,6.31,-0.05,-0.79,4752.00,3004.5062
2329,000001.SZ,19960104,6.18,6.32,6.15,6.31,6.24,0.07,1.12,3148.00,1967.4709
2330,000001.SZ,19960103,6.12,6.30,6.12,6.24,6.32,-0.08,-1.27,3841.00,2379.2193
2331,000001.SZ,19960102,6.35,6.35,6.30,6.32,NaN,NaN,NaN,2159.00,1367.7507

In [20]:
pro = ts.pro_api()

df=pro.stk_auction_o(ts_code='000014.SZ')
df.head(35)

,ts_code,trade_date,close,open,high,low,vol,amount,vwap
0,000014.SZ,20251023,25.00,25.62,25.62,24.80,1268700.0,32472320.00,25.60
1,000014.SZ,20251022,22.81,22.70,22.95,22.70,224020.0,5090061.12,22.72
2,000014.SZ,20251021,21.80,21.80,22.00,21.80,187567.0,4092072.64,21.82
3,000014.SZ,20251020,22.87,22.88,23.19,22.83,406800.0,9310286.72,22.89
4,000014.SZ,20251017,22.86,22.92,22.92,22.50,624700.0,14308884.48,22.91
5,000014.SZ,20251016,20.62,20.52,20.79,20.52,286200.0,5877265.92,20.54
6,000014.SZ,20251015,20.26,20.34,20.34,20.20,130100.0,2646007.04,20.34
7,000014.SZ,20251014,20.98,21.00,21.01,20.80,310000.0,6501809.28,20.97
8,000014.SZ,20251013,19.88,19.71,19.88,19.71,610800.0,12040802.56,19.71
9,000014.SZ,20251010,19.98,19.98,20.00,19.85,126100.0,2519319.20,19.98
10,000014.SZ,20251009,19.42,19.39,19.43,19.38,308600.0,5984620.80,19.39
11,000014.SZ,20250930,18.87,18.87,18.90,18.87,72740.0,1372692.80,18.87
12,000014.SZ,20250929,18.89,18.96,18.96,18.88,287400.0,5448464.00,18.96
13,000014.SZ,20250926,20.26,20.20,20.54,20.20,176400.0,3564729.92,20.21
14,000014.SZ,20250925,19.86,19.82,20.00,19.80,548200.0,10867621.12,19.82
15,000014.SZ,20250924,20.80,20.90,20.95,20.70,389800.0,8145292.80,20.90
16,000014.SZ,20250923,18.86,18.99,18.99,18.86,137900.0,2618068.96,18.99
17,000014.SZ,20250922,17.90,18.00,18.00,17.73,569800.0,10238636.80,17.97
18,000014.SZ,20250919,16.85,16.88,16.88,16.80,81800.0,1380467.04,16.88
19,000014.SZ,20250918,16.60,16.42,16.60,16.42,221620.0,3639439.36,16.42
20,000014.SZ,20250917,16.40,16.30,16.40,16.30,77300.0,1260284.96,16.30
21,000014.SZ,20250916,15.62,15.66,15.66,15.62,104000.0,1628340.96,15.66
22,000014.SZ,20250915,15.29,15.30,15.30,15.28,96900.0,1482523.04,15.30
23,000014.SZ,20250912,15.20,15.15,15.20,15.11,54600.0,827263.04,15.15
24,000014.SZ,20250911,15.16,15.15,15.25,15.15,88900.0,1348164.00,15.17
25,000014.SZ,20250910,15.00,15.00,15.00,14.98,132700.0,1990295.04,15.00
26,000014.SZ,20250909,14.63,14.65,14.69,14.63,210300.0,3080582.08,14.65
27,000014.SZ,20250908,14.50,14.42,14.50,14.42,368100.0,5310685.12,14.43
28,000014.SZ,20250905,13.59,13.59,13.59,13.59,33800.0,459342.00,13.59
29,000014.SZ,20250904,13.74,13.70,13.74,13.70,11900.0,163048.00,13.70
30,000014.SZ,20250903,13.90,13.89,13.90,13.89,40720.0,565624.80,13.89
31,000014.SZ,20250902,14.46,14.46,14.50,14.40,39700.0,574040.00,14.46
32,000014.SZ,20250901,14.19,14.20,14.20,14.19,88600.0,1258106.00,14.20
33,000014.SZ,20250829,14.60,14.64,14.64,14.60,57400.0,840316.00,14.64
34,000014.SZ,20250828,14.48,14.46,14.52,14.46,198260.0,2866962.56,14.46

In [ ]:
df = pro.fund_portfolio(ts_code='159813.SZ')

#df = df[df.]
df.sort_values(by='mkv',ascending=False)
#df.end_date.max()

'20250630'

In [3]:
df = pro.adj_factor( trade_date='20250826')
#df

In [2]:
df = pro.daily(ts_code='300502.SZ', start_date='20250825', end_date='20250826')
#df

ConnectionError: HTTPConnectionPool(host='api.waditu.com', port=80): Max retries exceeded with url: /dataapi/daily (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3006f7e0b0>: Failed to resolve 'api.waditu.com' ([Errno -2] Name or service not known)"))

In [15]:
df = pro.ths_index()
df

        ts_code       name  count exchange list_date type
0     882001.TI         安徽  159.0        A  20070808    R
1     882002.TI         北京  448.0        A  20070808    R
2     882003.TI         重庆   67.0        A  20070808    R
3     882004.TI        黑龙江   40.0        A  20070808    R
4     882005.TI         福建  168.0        A  20070808    R
...         ...        ...    ...      ...       ...  ...
1717  886102.TI    中国AI 50   50.0        A  20250310    N
1718  886103.TI  2025一季报预增  112.0        A  20250401    N
1719  886104.TI   2025中报预增  358.0        A  20250703    N
1720  886105.TI     雅下水电概念   86.0        A  20250721    N
1721  886106.TI  2025三季报预增   71.0        A  20251010    N

[1722 rows x 6 columns]

In [14]:
df = pro.fund_daily(ts_code='510330.SH', start_date='20250101', end_date='20250618', fields='trade_date,open,high,low,close,vol,amount')
df

    trade_date   open   high    low  close         vol       amount
0     20250618  4.008  4.024  3.996  4.017   382896.00   153574.446
1     20250617  4.015  4.022  4.000  4.014   440272.04   176617.125
2     20250616  4.000  4.018  3.996  4.015   423526.00   169788.251
3     20250613  4.023  4.028  3.992  4.004  1216787.53   487632.318
4     20250612  4.023  4.039  4.005  4.032   574727.00   231356.321
..         ...    ...    ...    ...    ...         ...          ...
104   20250108  3.971  3.992  3.908  3.963  3200416.00  1267465.456
105   20250107  3.939  3.974  3.929  3.973  2239739.00   885818.954
106   20250106  3.950  3.964  3.917  3.943  1583794.00   624004.760
107   20250103  4.002  4.013  3.944  3.963  2025111.00   805573.289
108   20250102  4.110  4.117  3.973  4.001  1768592.00   714820.885

[109 rows x 7 columns]